//
//  Meals.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class Meals: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _mealId: String?
    var _averageRating: NSNumber?
    var _creationDate: NSNumber?
    var _filePath: String?
    var _ingredients: String?
    var _lowercaseName: String?
    var _name: String?
    var _numRaters: NSNumber?
    var _ratersList: [String: String]?
    var _rating: NSNumber?
    var _recipe: String?
    var _s3Key: String?
    var _updateDate: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "mealsapp-mobilehub-1459387644-meals"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_mealId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_mealId" : "mealId",
               "_averageRating" : "average_rating",
               "_creationDate" : "creation_date",
               "_filePath" : "file_path",
               "_ingredients" : "ingredients",
               "_lowercaseName" : "lowercase_name",
               "_name" : "name",
               "_numRaters" : "num_raters",
               "_ratersList" : "raters_list",
               "_rating" : "rating",
               "_recipe" : "recipe",
               "_s3Key" : "s3Key",
               "_updateDate" : "update_date",
        ]
    }
}
